### ISSUE TITLE
Including unarchived assets on the server

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#100]
I've now come up with at 3 use cases that suggest we should tweak the way we store asset archives.

1. For nextflow use of refgenie, they want an s3 source of the refgenie assets *unarchived*.  Right now all we store on s3 is the archived version.

2. For a UCSC assemblyhub, refgenie/refgenie#219, we need to host a twobit file. If we had a twobit asset in refgenie, we'd have it on s3 wrapped up in an archive. But we don't want that archive.

3. Same thing for integration with JBrowse, which wants:

```
{
  "type": "IndexedFastaAdapter",
  "fastaLocation": {
    "uri": "https://jbrowse.org/genomes/hg19/fasta/hg19.fa"
  },
  "faiLocation": {
    "uri": "https://jbrowse.org/genomes/hg19/fasta/hg19.fa.fai"
  }
}
```

so it needs a URL to the `.fa` and `.fa.fai` files directly.

So, this leads to  what we should do: 

- no change to the client. It pulls the archive and unzips it as normal.
- the API should offer endpoints that provide access to individual seek keys for an asset.
- when pushing the assets, we should push the archive, as well as unarchived versions for the direct access endpoints.

**Comment by nsheff** [comment]
Here's an endpoint idea:  `v3/asset/{genome_digest}/seek/{asset}/{seek_key}?tag=default`

Example: `v3/asset/09caecc78ed519cf256668505641345c9d1b7011426f66ba/seek/fasta/fai?tag=default`

**Comment by nsheff** [comment]
A few thoughts:

1. What should the API enpoint be called? Right now it's `assets/asset_file_path/{digest}/...` -- Do you want to use `seek` or `seekr` in there for analogy to the CLI? Just thinking out loud...
2. Should we have a parameter `?protocol=s3|http` (default to `http`) ? I think to enable the s3 links, we'd need a new prefix attribute in the refgenie archive config file used by `refgenieserver`. it could just be `s3_bucket` or `s3_prefix` or something.

**Comment by stolarczyk** [comment]
> What should the API enpoint be called? Right now it's assets/asset_file_path/{digest}/... -- Do you want to use seek or seekr in there for analogy to the CLI? Just thinking out loud...

I'm not sold on `asset_file_path` in there either... But I'm also not sure if introducing this tight terminology coupling between refgenieserver REST API and CLI is a good idea. I think it's more important that the REST API is easy to understand for _anyone_ consuming it. `seekr` keyword does not hint at what the return value of this endpoint is.  For example, we don't use `pull` keyword for the endpoint that serves the archive, but `archive`.

> Should we have a parameter ?protocol=s3|http (default to http) ? I think to enable the s3 links, we'd need a new prefix attribute in the refgenie archive config file used by refgenieserver. it could just be s3_bucket or s3_prefix or something.

Yeah, I thought about it briefly as well.. the issue is that we provide complete flexibility (which is great) in terms of the remote asset provider -- using AWS S3 is just our choice.

**Comment by nsheff** [comment]
>  I'm also not sure if introducing this tight terminology coupling between refgenieserver REST API and CLI is a good idea

Alright, I see your point here. I'm fine with that I think.

> the issue is that we provide complete flexibility (which is great) in terms of the remote asset provider -- using AWS S3 is just our choice.

True, but S3 is so ubiquitous now that it's now its own protocol, like http... other providers (like backblaze) provide s3-compatible interfaces, for example. So, we can use any provider, as long as it's s3 compatible. but the downstream consumption tools will need to know that it's an s3 url to consume it correctly. So, I think using 's3' is still the right choice. We would have to add others for other storage systems anyway, if they are not s3 compatible.

**Comment by stolarczyk** [comment]
> True, but S3 is so ubiquitous now that it's now its own protocol, like http... other providers (like backblaze) provide s3-compatible interfaces, for example.

ok, I wasn't aware of that.

**Comment by nsheff** [comment]
> ok, I wasn't aware of that.

https://devblogs.microsoft.com/cse/2016/05/22/access-azure-blob-storage-from-your-apps-using-s3-api/

looks like azure and google cloud aren't natively s3 compatible, but there are workarounds...  

do you think there's a more flexible solution we'd need to arrange? I mean, from refgenie's perspective it's just returning a URL. It's just a question of the underlying service for that URL, right? the downstream stuff has to deal with whatever it is. We could already put an s3 prefix in the one as it currently is. So maybe it's a mapping, like:

```
remotes:
  http: 
    prefix: http://data.blablbah...
    description: This is an http compatible endpoint...
  s3: 
    description: ...
    prefix: s3://blahblah
  xzy: 
    description: ...
    prefix: whatever://whatever
```

and then you can use `?remote_class=s3|http|xzy`, and a `protocols` endpoint would return the available URI types?
