### ISSUE TITLE
How should URLs be formatted?

### ISSUE THREAD

**Issue by jpsmith5** [databio/refgenieserver#101]
Currently, genome splash pages, asset pages, et cetera follow a non-uniform URL structure. 

For example, a genome splash page utilizes a parental `genome/` URL: `http://rg.databio.org/genome/10c566e9f7c867a2eb27fd8606254a5a3d45aee8c175a07e/splash`

But, a related asset _for_ that genome changes the structure to: `
http://rg.databio.org/v3/asset/10c566e9f7c867a2eb27fd8606254a5a3d45aee8c175a07e/bowtie2_index/splash?tag=default`

A few thoughts:
1. Enabling human-readable URL entry.
Current: `http://rg.databio.org/genome/10c566e9f7c867a2eb27fd8606254a5a3d45aee8c175a07e/splash`
Instead: `http://rg.databio.org/genome/hg19/splash`
 - Both go to the same place essentially. And then the URL construction could also change...
2. Changing the URL structure to go from most broad -> most specific. e.g.
`http://rg.databio.org/index/hg19` # splash page
`http://rg.databio.org/index/asset/recipe/bowtie2_index/hg19` # asset endpoint _for_ the recipe _for_ bowtie2_index _for_ hg19
 - Therefore, if I wanted to see how this was different for hg38, I could just manually change that in the URL itself as opposed to needing to browse back to the refgenomes home page and finding that genome splash page.
3. Alternatives to `asset/`.  Maybe this doesn't need it's own `/`, but could be:
```
asset_archive/bowtie2_index/hg38
asset_digest/bowtie2_index/hg38
asset_recipe/bowtie2_index/hg38
```

**Comment by stolarczyk** [comment]
# refgenieserver API design

## nested

Use path hierarchy to restrict the response

### `genomes` collection

**GET**

- `/genomes` - lists "genomes" resource elements
  - `/genomes/{genome}`
    - `/genomes/{genome}/description`
    - `/genomes/{genome}/alias`
    - `/genomes/{alias}/genome_digest` (inconsistent)
    - ...
    - `/genomes/{genome}/assets` - lists "assets" resource elements
      - `/genomes/{genome}/assets/{asset}`
        - `/genomes/{genome}/assets/{asset}/seek_keys`
        - `/genomes/{genome}/assets/{asset}/default_tag`
        - ...
        - `/genomes/{genome}/assets/{asset}/tags` - lists "tags" resource elements
        - `/genomes/{genome}/assets/{asset}/tags/{tag}`
          - `/genomes/{genome}/assets/{asset}/tags/{tag}/asset_digest`
          - `/genomes/{genome}/assets/{asset}/tags/{tag}/archive_digest`
          - ...

### `recipes` collection (future)

**GET**

- `/recipes` - lists "recipes" resource elements
  - `/recipes/{recipe}`
    - `/recipes/{recipe}/author`
    - `/recipes/{recipe}/command_list`
    - `/recipes/{recipe}/parents`
    - `/recipes/{recipe}/children`
    - ...

**POST**

...

**DELETE**

...

---

## non-nested

Use query parameters to restrict the response

### `genomes` collection

**GET**

- `/genomes` - lists "genomes" resource elements
  - `/genomes/{genome}`
    - `/genomes/{genome}/description`
    - `/genomes/{genome}/alias`
    - ...

### `assets` collection

**GET**

- `/assets?genome={genome}` - lists "assets" resource elements
  - `/assets/{asset}?genome={genome}`
    - `/assets/{asset}/seek_keys?genome={genome}`
    - `/assets/{asset}/default_tag?genome={genome}`

### `tags` collection

**GET**

- `/tags?genome={genome}&asset={asset}` - lists "assets" resource elements
  - `/tags/{tag}?genome={genome}&asset={asset}`
    - `/tags/{tag}/asset_digest?genome={genome}&asset={asset}`
    - `/tags/{tag}/archive_digest?genome={genome}&asset={asset}`

### `recipes` collection (future)

**GET**

- `/recipes` - lists "recipes" resource elements
  - `/recipes/{recipe}`
    - `/recipes/{recipe}/parents`
    - `/recipes/{recipe}/command_list`
    - ...

**POST**

...

**DELETE**

...

**Comment by nsheff** [comment]
The way we refer to all entities follows this pattern: `{genome}/{asset}.{seek_key}:{tag}`

Can we mimic as close as possible to using that in the API?


-`/assets/description/{genome}/{asset}.{seek_key}:{tag}`
-`/tags/{genome}/{asset}.{seek_key}:{tag}`
-`/genomes/description/{genome}`

**Comment by nsheff** [comment]
each endpoint follows a general system:
```
{collection}/{endpoint_name}/...
```
The end of the endpoint is always the registry path referring to the entity and can be, depending on the endpoint:
-  `{genome}/{asset}` (most common)
- `{genome}` (also common)
- `{asset}` -- infrequently... maybe only for `/genomes/list_by_asset/{asset}`
- `{genome}/{asset}/{seek_key}` -- probably nothing right now, but will use in the future for cloud paths to cloud assets.

Many of these can add `?tag=tagname` as an optional query parameter.

Examples of endpoints that fit this framework:

- `/assets/list_by_genome/{genome}?tag={tagname}`
- `/assets/seek_keys/{genome}/{asset}`
- `/assets/archive/{genome}/{asset}`
- `/assets/digest/{genome}/{asset}`
- `/assets/build_log/{genome}/{asset}`
- `/assets/recipe/{genome}/{asset}`
- `/assets/splash/{genome}/{asset}`
- `/genomes/list_by_asset/{asset}`
- `/genomes/digest/{genome}`
- `/genome/attributes/{genome}`
- `/genomes/list_all` (no params, list genomes)
- `/assets/list_all` (list all assets?)

Just some ideas, not sold on any of this.

**Comment by nsheff** [comment]
another possibility is to just not have collections for endpoints, and just name each endpoint at the top level:


- `/asset_list_by_genome/{genome}?tag={tagname}`
- `/asset_seek_keys/{genome}/{asset}`
- `/asset_archive/{genome}/{asset}`
- `/asset_digest/{genome}/{asset}`
- `/asset_build_log/{genome}/{asset}`
- `/asset_recipe/{genome}/{asset}`
- `/asset_splash/{genome}/{asset}`
- `/genome_list_by_asset/{asset}`
- `/genome_digest/{genome}`
- `/genome_attributes/{genome}`
- `/genomes_list_all` (no params, list genomes)
- `/assets_list_all` (list all assets?)
