### ISSUE TITLE
TgMap file

### ISSUE THREAD

**Issue by k3yavi** [databio/refgenieserver#103]
Hey guys,

Thanks again for maintaining the great tool.
I got another request, for using alevin users often need a transcript to gene id mapping tsv file, which they have to create posthoc. Is it possible or advisable to include the tgMap file with the salmon indices ?

**Comment by nsheff** [comment]
do you think it would be a separate asset? or bundled with the salmon indices?

**Comment by k3yavi** [comment]
I feel it'd be great if we can bundle it inside the salmon indices. However if it needs major restructuring on the refgenie front or it'd benefit other tools' indices also, then probably it's better to create a separate asset ? All we need from the salmon/alevin front is a consistent way to suggest users for generating the tgMap file. In theory we can use the GTF asset already present and write a script around it but I just wanted to run it with you guys.

**Comment by nsheff** [comment]
2 questions: 

1. how big is the file?
2.  would you ever want the salmon indexes without that file?

**Comment by k3yavi** [comment]
I don't think it's a big file probably a few mb. Yea, the bulk mode of salmon won't need it, only the single-cell mode (alevin) would (always) need this file.

**Comment by nsheff** [comment]
does salmon expect them to be living in some particular folder/naming orientation relative to one another? or can the be passed separately?

**Comment by k3yavi** [comment]
It's passed separately.

**Comment by nsheff** [comment]
OK great. Can you provide a recipe for how to create it?

**Comment by k3yavi** [comment]
Usually I do the following:
```
wget --content-disposition  -nv http://refgenomes.databio.org/v2/asset/hg38/salmon_partial_sa_index/archive?tag=default
tar -xvzf salmon_partial_sa_index__default.tgz
grep "^>" salmon_partial_sa_index/gentrome.fa | cut -d " " -f 1,7 --output-delimiter=$'\t' - | sed 's/[>"gene_symbol:"]//g' > txp2gene.tsv
```

But it only works with partial salmon index, not with the full genome.

**Comment by stolarczyk** [comment]
I created the `tgMap` recipe in refgenie: https://github.com/refgenie/refgenie/commit/7d1f1ac82a3661959345efcee3ea4667cc780b8f. But had to add a `tr` step since not all implementations of `cut` support `--output-delimiter` option.


@k3yavi, can you confirm this looks alright? Here's a couple of lines of the result for hg38 genome:

```
[mstolarczyk@MichalsMBP refgenie]: head `refgenie seek hg38/tgMap -c g.yml`
ENST00000631435.1	TRBD1
ENST00000415118.1	TRDD1
ENST00000448914.1	TRDD3
ENST00000434970.2	TRDD2
ENST00000632684.1	TRBD1
ENST00000439842.1	IGHD7-27
ENST00000390567.1	IGHD1-26
ENST00000452198.1	IGHD6-25
ENST00000390569.1	IGHD5-24
ENST00000437320.1	IGHD4-23
```

**Comment by k3yavi** [comment]
My apologies for the late response @stolarczyk . It looks great, thanks for adding this.

**Comment by stolarczyk** [comment]
@k3yavi, I built tgMap assets for the genomes we had salmon_partial_sa_indexes for. They are currently served with our development refgenieserver instance. Here's an example: [hg38/tgMap](http://rg.databio.org/v3/assets/splash/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/tgMap?tag=default)

**Comment by k3yavi** [comment]
Look perfect @stolarczyk . Thanks for adding it.
