### ISSUE TITLE
add tree endpoint

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#110]
- [x] add to archiver: `tree asset > tree_files.txt` -- put alongside logs and stuff that are external to the asset.
- [x] add an endpoint to serve that file
- [x] add a link to the endpoint on the asset splash page,
- [x] and maybe hit that endpoint to display its contents on the splash page as well?

**Comment by stolarczyk** [comment]
went with `find` in the end to avoid adding `tree` dependency as this command might not be installed on some systems.

Example endpoint: http://rg.databio.org/v3/assets/dir_contents/94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta?tag=default

**Comment by stolarczyk** [comment]
another update: instead of calling `find` in a subprocess and storing results in a text file I used `os.listdir` and stored the files in JSON, which is much more convenient for web applications.
