### ISSUE TITLE
Links to new cloud-based endpoints

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#113]
Related to #100.

We should add some links on the asset splash pages, to make it easier to find stuff. Ideally we don't have to use the API docs, but can browse the assets and then click on whatever link. Here's a list

At least we should have:
- full archive via either http or s3 (or, whatever is provided in `remotes`, for each remote)
- individual seek key items for each remote

Maybe start thinking about
- individual items that aren't seek keys for each remote -- would require new way to include this in the config 
- link to the 'dir' for each remote (the dir seek key which would just be the asset folder)

**Comment by stolarczyk** [comment]
> individual seek key items for each remote

that's done. LMK what you think: http://rg.databio.org/v3/assets/splash/43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta?tag=default

Also, I used the latest refgenie@dev, so the default `dir` seek key is added in every asset, which points to a dot (`.`), which looks a bit unsatisfying. On the other hand, I like the fact that it's not treated in a special way. This sort of solves the point below

> link to the 'dir' for each remote (the dir seek key which would just be the asset folder)

**Comment by nsheff** [comment]
that's great! style-wise, I can't immediately tell they are links though, since you're using buttons with bold black. I think it would be more clear if they followed the same link style as all the other endpoint links. maybe just with text like [[http]() | [s3]()]. and if you shift to the front then they will line up. So,

seek_keys:
    [[http]() | [s3]()] fasta: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa 
    [[http]() | [s3]()] fai: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa.fai 
    [[http]() | [s3]()] chrom_sizes: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.chrom.sizes 
    [[http]() | [s3]()] dir: . 


Do you think the dot should point to assets like:
```
http://.../43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta__default/.
```
or
```
http://.../43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta__default/
```

I think the latter is better. Otherwise people will just have to remove that dot


## unneeded comma

just saw this unneeded comma here: 
![image](https://user-images.githubusercontent.com/5271009/112683412-e2926800-8e47-11eb-89b3-7d2419e6abe7.png)

**Comment by stolarczyk** [comment]
I corrected the style.

> I think the latter is better. Otherwise people will just have to remove that dot

So you're essentially suggesting to add `{"dir": ""}` key-value pair to seek_keys in the recipe, instead of `{"dir": "."}`?

**Comment by nsheff** [comment]
> So you're essentially suggesting to add {"dir": ""} key-value pair to seek_keys in the recipe, instead of {"dir": "."}?

hmm... I guess so. What do you think?

**Comment by stolarczyk** [comment]
I think this makes sense. The only downside in my opinion is the fact that we will need to treat this seek_key individually not to end up with `dir` pointing to nothing in the asset page. Or, maybe that's fine actually?

**Comment by stolarczyk** [comment]
I tried using this in practice and the empty value for `dir` seek_key introduces some problems. It is interpreted as `None`, as opposed to `str` in regular seek_keys, which may cause some nasty bugs down the road. I'm not sure if it's worth going down this path...

Alternatively, to solve the issue that inspired us to switch from `{"dir": "."}` to `{"dir": ""}` we could programmatically strip any trailing `.` from the paths before serving.

**Comment by stolarczyk** [comment]
I decided to simply not append the seek_key target for the `dir` seek_key and it solved it: http://rg.databio.org/v3/assets/file_path/94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/bowtie2_index/dir?tag=default&remoteClass=s3

**Comment by nsheff** [comment]
Just thinking out loud... do you think the links should lead to actual files, as opposed to links to links? I mean the links on the splash page.

**Comment by stolarczyk** [comment]
I see some use in both, but mostly in the links, which can be used to get the file. I don't know if you remember, but initially, I implemented an endpoint that served the file and we decided to remove it since the endpoint serving the link _almost_ accomplishes the file serving goal.

**Comment by stolarczyk** [comment]
Also, for assets like bowtie2_index it would be tricky.

**Comment by nsheff** [comment]
> I don't know if you remember, but initially, I implemented an endpoint that served the file and we decided to remove it since the endpoint serving the link almost accomplishes the file serving goal.

Yes I know; this is slightly different... it's a link and doesn't necessarily need to be an endpoint. So you can make these direct links without an endpoint that returns the files; but also provide the endpoint that returns the link.

> Also, for assets like bowtie2_index it would be tricky.

This is actually one of the things I'd like to do, is basically reproduce this interface: https://benlangmead.github.io/aws-indexes/bowtie

This is tricky because they are not seek keys, though.

**Comment by stolarczyk** [comment]
ok, so this requires a new concept of serving any file from the asset directory, regardless of the fact if the seek_keys point to them.

We could somehow use the generated [asset dir contents files](http://awspds.refgenie.databio.org/rg.databio.org/94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/asset_dir_contents_bowtie2_index__default.txt).

**Comment by nsheff** [comment]
Do you think it would make sense to define these as another, lower class of seek key, that doesn't provide seek key access but does provide API access?

**Comment by stolarczyk** [comment]
I managed to mimic the interface you linked without the special seek_key class. You can check it out [here](http://rg.databio.org/v3/assets/splash/94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/bowtie2_index?tag=default)

**Comment by nsheff** [comment]
I like that!

**Comment by nsheff** [comment]
the only thing I'd change is maybe *not* force-uppercase, and just follow the casing in the config file:

https://github.com/refgenie/rg.databio.org/blob/9d1d6f21056977b66a344e45a85c5b6875387dad/config/refgenie_config_archive.yaml#L6

For HTTP and S3 it seems alright to force upper, but what if the remote was something else?
