### ISSUE TITLE
can't find salmon-sa-index .

### ISSUE THREAD

**Issue by k3yavi** [databio/refgenieserver#118]
Hi guys,

I was wondering, did we remove the salmon-genome indices from the refgenie server, it was relatively big in size ~20G for hg38 ? There was a recent issue on salmon repo which raised the concern and I also can't seem to find that online. My apologies if I am looking at wrong places. 

https://github.com/COMBINE-lab/salmon/issues/658

**Comment by stolarczyk** [comment]
We have recently rebuilt all the assets due to refgenie system updates and I'm not sure why, but these builds have been skipped. The jobs are running now and the assets should be on the server in the next few days.

**Comment by k3yavi** [comment]
Thanks @stolarczyk , much appreciated .

cc @JennyFrodoBrynnNick

**Comment by stolarczyk** [comment]
the salmon_sa_index assets are back, e.g. [`hg38/salmon_sa_index`](http://refgenomes.databio.org/v3/assets/splash/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/salmon_sa_index?tag=default)

**Comment by k3yavi** [comment]
Thanks @stolarczyk for super fast turnaround.
