### ISSUE TITLE
hg38 salmon_sa_index reference fasta

### ISSUE THREAD

**Issue by nbrittain** [databio/refgenieserver#121]
Hi,

I have used the hg38/salmon_sa_index:default from refgenie to run salmon quant. For some other work I need to determine what was the source of the fasta used to create this, is there a way to determine the source eg Ensembl, Gencode etc. for this asset? On the build log there is a code for the parent .fa file which appears to have been from your servers and I don't think I can view further details.

Many thanks,

Nick

**Comment by nsheff** [comment]
You can find all the relevant assets here: http://refgenomes.databio.org/v3/genomes/splash/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4

Note the description here: Description: The GCA_000001405.15 GRCh38_no_alt_analysis_set from NCBI 

see, here is the fasta in question: http://refgenomes.databio.org/v3/assets/splash/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/fasta?tag=default

And you can actually see the exact parents of the salmon index asset here: http://refgenomes.databio.org/v3/assets/splash/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/salmon_sa_index?tag=default

(which would lead you to the above fasta asset)

**Comment by nbrittain** [comment]
Excellent, thanks very much Nathan

**Comment by NBrittain** [comment]
Is there a way to view which Ensembl transcriptome version was used for this reference?
