### ISSUE TITLE
add genome level tarball attributes in archiver

### ISSUE THREAD

**Issue by stolarczyk** [databio/refgenieserver#18]
originally proposed by @nsheff in #17 

> the 'all asset' link also needs a checksum and filesize. we need a way to build this information into the 'archive' command

**Comment by nsheff** [comment]
if we just archive them twice, then we have to store twice as much data on the server; individual archives and then the combined one.  can we think of another solution?

1. we only keep the parent tar on disk; when an archive is requested via the API, we extract that individual tgz from the tar. it should be pretty fast (?)
2. we only keep the individual tars on disk. when a parent tar is requested, we build it by quickly tarring up the stuff and sending that on the fly.
3. we just keep both, storing each asset twice, doubling our required disk space.

**Comment by stolarczyk** [comment]
we decided not to store the genome level tarballs at all. The same goal can by achieved by looping through the assets by `refgenie pull`
