### ISSUE TITLE
Multiple sources of truth

### ISSUE THREAD

**Issue by vreuter** [databio/refgenieserver#20]
There's a config file in this project's root that differs in structure from the one in, e.g., `refgenconf`'s root. The one here should move to `refgenconf`, and then the one here should point to that one.

**Comment by nsheff** [comment]
agreed! with the one caveat that this config file refers to stuff in this repository and specific to the `archive` command, which is beyond what is minimally required for the `refgenconf` file to work... anyway, I'm fine with doing as you suggest anyway if you wish

**Comment by vreuter** [comment]
I mean, I don't _need_ a resolution...I just noticed this when working within in-code data in a test suite, that's mirroring the older structure. I'm OK with it and understand it for ease of use and a sort of meta-independence between the projects, but I could see upside with the single truth source. Anyway, no big deal, just a thought.

**Comment by nsheff** [comment]
I believe this is no longer an issue with the new configs.
