### ISSUE TITLE
are mounting app docs incorrect?

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#21]
in our directions we use -`v` to mount the `/app` dir. 

I know you used to need to do this, but with the switch to importing uvicorn to run on the command line, is this still necessary? can we updated the docs if not?

**Comment by stolarczyk** [comment]
yeah, this is not necessary anymore

**Comment by nsheff** [comment]
did you close this issue but not actually solve it ? or is it solved somewhere but just not in master yet ?

**Comment by stolarczyk** [comment]
I thought you've resolved it with https://github.com/databio/refgenieserver/commit/cbad6b3d1831f705a301715ec22ad3baad62b636 then

**Comment by nsheff** [comment]
ah. I sort of half did it. I think I got it all now.
