### ISSUE TITLE
refgenie pull consistently fails to retrieve complete asset (large asset only?)

### ISSUE THREAD

**Issue by jpsmith5** [databio/refgenieserver#23]
Not sure if this is related to the size of the asset, but refgenie pull consistently is unable to retrieve the complete file.

```
$ refgenie pull -g hg38 -a bowtie2
Starting pull for 'hg38/bowtie2'
'hg38/bowtie2' archive size: 3.5GB
Downloading URL: http://refgenomes.databio.org/asset/hg38/bowtie2/archive
hg38/bowtie2:  16%|████████████████████████▉                                                                                                                                   | 600M/3.75G [00:19<01:44, 30.2MB/s]
<urlopen error retrieval incomplete: got only 600489984 out of 3749238990 bytes>
'hg38/bowtie2' download incomplete

$ refgenie pull -g hg38 -a bowtie2
Starting pull for 'hg38/bowtie2'
'hg38/bowtie2' archive size: 3.5GB
Downloading URL: http://refgenomes.databio.org/asset/hg38/bowtie2/archive
hg38/bowtie2:   5%|███████▊                                                                                                                                                    | 186M/3.75G [00:10<03:22, 17.6MB/s]
<urlopen error retrieval incomplete: got only 186474496 out of 3749238990 bytes>
'hg38/bowtie2' download incomplete

$ refgenie pull -g hg38 -a bowtie2
Starting pull for 'hg38/bowtie2'
'hg38/bowtie2' archive size: 3.5GB
Downloading URL: http://refgenomes.databio.org/asset/hg38/bowtie2/archive
hg38/bowtie2:  58%|██████████████████████████████████████████████████████████████████████████████████████████▏                                                                | 2.18G/3.75G [01:06<00:47, 32.8MB/s]
<urlopen error retrieval incomplete: got only 2181976064 out of 3749238990 bytes>
'hg38/bowtie2' download incomplete

$ refgenie pull -g hg38 -a bowtie2
Starting pull for 'hg38/bowtie2'
'hg38/bowtie2' archive size: 3.5GB
Downloading URL: http://refgenomes.databio.org/asset/hg38/bowtie2/archive
hg38/bowtie2:  14%|█████████████████████                                                                                                                                       | 507M/3.75G [00:27<02:57, 18.2MB/s]
<urlopen error retrieval incomplete: got only 506863616 out of 3749238990 bytes>
'hg38/bowtie2' download incomplete

$ refgenie pull -g hg38 -a bowtie2
Starting pull for 'hg38/bowtie2'
'hg38/bowtie2' archive size: 3.5GB
Downloading URL: http://refgenomes.databio.org/asset/hg38/bowtie2/archive
hg38/bowtie2:  14%|█████████████████████▌                                                                                                                                      | 517M/3.75G [00:28<02:58, 18.2MB/s]
<urlopen error retrieval incomplete: got only 517259264 out of 3749238990 bytes>
'hg38/bowtie2' download incomplete

$ refgenie pull -g hg38 -a bowtie2
Starting pull for 'hg38/bowtie2'
'hg38/bowtie2' archive size: 3.5GB
Downloading URL: http://refgenomes.databio.org/asset/hg38/bowtie2/archive
hg38/bowtie2:  26%|█████████████████████████████████████████▏                                                                                                                  | 990M/3.75G [00:31<01:28, 31.0MB/s]
<urlopen error retrieval incomplete: got only 989806592 out of 3749238990 bytes>
'hg38/bowtie2' download incomplete

```

**Comment by nsheff** [comment]
this didn't help.

@michalstolarczyk 

I tnoice the `download_asset` function is not asynchronous. could that be an issue? in fact, shouldn't all the endpoints be `async` ?

https://www.starlette.io/responses/#fileresponse

**Comment by nsheff** [comment]
based on [this answer](https://stackoverflow.com/a/48949959) I think `FileResponse` is the correct thing to use, so I think we're right on that point at least.

**Comment by nsheff** [comment]
Ok I've tried updating to `async` both with and without specifying the media_type and none of that seems to change anything. my pulls are still failing after about 15-45 seconds.

**Comment by nsheff** [comment]
@nmagee isolated this to a problem with the DCOS.

we're temporarily pointing a different server, which works. I just updated the DNS, to this should be resolved now.

in the future we'll figure out how to get it working on the new hardware, but for now, it appears to be working just fine on the dev machines. Thanks neal

**Comment by nmagee** [comment]
Thanks for being one of my guinea pigs, as always, @nsheff  ;-)

**Comment by stolarczyk** [comment]
> @nmagee isolated this to a problem with the DCOS.
> 
> we're temporarily pointing a different server, which works. I just updated the DNS, to this should be resolved now.
> 
> in the future we'll figure out how to get it working on the new hardware, but for now, it appears to be working just fine on the dev machines. Thanks neal

Following this change the pushes to `master` are not reflected at http://refgenomes.databio.org/, but only at http://refgenieserver.uvadcos.io/. However, the latter throws `Internal server error`s when the assets are to be served, so it might not have an access to the required filesystem (?). 

Is that intentional as it is just a temporary solution? Or we need some adjustments for the http://refgenomes.databio.org/ to be updated?

**Comment by nmagee** [comment]
@michalstolarczyk -- good questions. In our quick hardware reversion last Friday I failed to wire up pushes to master and the running app itself. I'll correct that today so that changes to `master` will show up in both places, as well as figure out the filesystem issue.

I'm considering switching out the load balancers for DCOS to be entirely driven by the Traefik LB, which (I hope and think) may resolve the migration issues.

**Comment by nmagee** [comment]
@michalstolarczyk @nsheff -- progress on this front: Using Traefik LB for the primary load balancer in DCOS did resolve this reported issue:

```
[nmagee@storage01 tmp]$ wget http://refgenomes.uvasomrc.io/asset/rn6/bismark_bt1/archive
--2019-06-21 08:45:27--  http://refgenomes.uvasomrc.io/asset/rn6/bismark_bt1/archive
Resolving refgenomes.uvasomrc.io (refgenomes.uvasomrc.io)... 128.143.8.170
Connecting to refgenomes.uvasomrc.io (refgenomes.uvasomrc.io)|128.143.8.170|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7595086265 (7.1G) [application/octet-stream]
Saving to: ‘archive’

100%[===========================================================================================================>] 7,595,086,265 16.4MB/s   in 7m 33s 

2019-06-21 08:53:01 (16.0 MB/s) - ‘archive’ saved [7595086265/7595086265]
```

I'm going to test Traefik's functionality in other respects to make sure it's entirely suitable, but I think it can work well, all-around. Give me a week or two to make that determination. If we keep Traefik in place we can move the entire stack (production and dev) back over to DCOS.

**Comment by nsheff** [comment]
wow, great! Thanks.
