### ISSUE TITLE
dev branch

### ISSUE THREAD

**Issue by nmagee** [databio/refgenieserver#25]
Per request of @nsheff added a `dev` branch to the project, based on `045ae81`. Deployments using `.travis.yml` have been updated as well for automation. Build/deploys are taking ~60 seconds. [Follow Travis-CI here](https://travis-ci.org/databio/refgenieserver/builds)

**DEV/Development Branch** 
* http://dev.refgenomes.uvasomrc.io/
* http://dev.refgenomes.databio.org/ [DNS required]
* http://dev.refgenomes.uvadcos.io/ [DCOS preview - in testing]

**MASTER/Production Branch** 
* http://refgenomes.uvasomrc.io/
* http://refgenomes.databio.org/
* http://refgenomes.uvadcos.io/ [DCOS preview - in testing]

**Merging Upstream:**
* Minor tweaks and changes can be done via merge.
* New features / testing / UAT should be done via PRs.

**To Do:**
- [ ] Update DNS for `dev.refgenomes.databio.org` point as CNAME to `dev1.uvasomrc.io`.
- [ ] Continue testing of Traefik LB per #23 to determine move to DCOS for both branches. This includes Redis data migration, if required.

**Comment by nsheff** [comment]
Proposal:  We typically use `dev` for pushing unpolished changes, so we should think differently for this rep. We use a new branch, 'sandbox', for temporary storage, untested changes, stuff we're doing locally.  When we're ready to deploy that to the dev server, we PR into dev. final release is the PR from dev to master.

The only thing about this is that I'm used to dev being like what I call 'sandbox' here, so maybe I've shot myself in the foot with these names... open to ideas/thoughts.

**Comment by nsheff** [comment]
In other words, maybe the second 'developmental server' deploy should *actually* have been called something else ('staging'?) just for consistency with other projects?

No big deal here, just brainstorming.

**Comment by vreuter** [comment]
If you're worried about changes inadvertently going into the test deployment, you could keep `dev` conceptually "dev" and make the test reployment something like `deploy`.

**Comment by nmagee** [comment]
@vreuter has a good point -- `master` is easily (for my automated fingers) a branch I might accidentally push to, so an alt naming convention might be of help.

As for dev, staging, master branches+deployments, feel free to name it whatever you like -- I think 2 server-deployed branches is sufficient. (Remember when we had 3 levels for LOLAweb? It felt like too much.)

**Comment by nsheff** [comment]
Ok I think we all agree on concept but not on name:

the `dev` branch should **not** have an associated test server
the test server should be on a different branch. We have 3 suggestions for name of that branch:

- sandbox
- deploy
- staging

is there a community standard here?

the staging server would then be `staging.refgenomes.databio.org` (or `deploy.refgenomes.databio.org` or whatever we decide to name it). it should be named the same thing as the branch.

We will develop onto dev as normal. when ready to test, we PR to `X`, which deploys to `x.refgenomes.databio.org`.

What is X? Everyone vote. @michalstolarczyk

**Comment by nsheff** [comment]
by my searches, `staging` seems to be the accepted name for this type of setup. http://guides.beanstalkapp.com/deployments/best-practices.html

the `staging` branch, and `staging.URL` are used to test a deployment before merging to master. So, staging has my vote.

**Comment by stolarczyk** [comment]
I'm fine with `staging`

**Comment by nmagee** [comment]
`staging` is good. And @nsheff there is no universal convention here -- different shops seem to have their standard and they stick to it. It makes sense to them, but might be very different next door.

Likewise, relying on `master` (Git) or `latest` (Docker) for the canonical / production version-branch is the way to go, or totally frowned upon.

If we don't yet have a `staging` branch here I will create one, launch that in DCOS, and set up automatic deployments.

**Comment by nmagee** [comment]
@michalstolarczyk -- should I create `staging` based off of the `dev` branch you've been working on? Or from a fresh new branch off of `master`?

**Comment by stolarczyk** [comment]
Let's create a fresh one from `master`

**Comment by nmagee** [comment]
Okay, that's done. A clean `staging` branch has been created and pushed, with Travis snapped in correctly. One push has deployed automatically so I think we're all set.

The site has been loaded in DCOS, under these names:

- http://staging.refgenomes.uvadcos.io
- http://staging.refgenomes.databio.org

@nsheff could you please create a CNAME record `staging.refgenomes.databio.org` pointed to `loadbalancer.uvadcos.io`?

**Comment by nmagee** [comment]
DNS is in place now, and the pieces of a working `staging` branch appear to be all set.

**Comment by nsheff** [comment]
yep, appears to be working. thanks!
