### ISSUE TITLE
staging config

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#41]
@nmagee can we make the staging server operate on a different genome config file from the main server?

**Comment by nmagee** [comment]
@nsheff yeah I can set that up. Do you have a config file in mind already?

**Comment by nmagee** [comment]
So as deployed in DCOS, this will be a simple change. It's pulling the `databio/refgenieserver:staging` image to run, then executing this command, which can easily be modified:
```
refgenieserver -c /genomes/genomes.yaml serve
```
Just let me know a different YAML to point to and I can update it.

**Comment by nmagee** [comment]
http://staging.refgenomes.databio.org/

**Comment by nsheff** [comment]
@michalstolarczyk probably has a config he can point to.

**Comment by nsheff** [comment]
we are changing the config format... hence the problem...

**Comment by stolarczyk** [comment]
@nmagee, on `staging` we'd like to use this file: `/project/shefflab/refgenomes_archive/genomes_staging.yaml`

Additionally, we'd like to use a separate Dockerfile for the staging container, since we expect to test non-released requirements of `refgenieserver`. Do you think you can set it up this way?
[`staging.Dockerfile`](https://github.com/databio/refgenieserver/blob/dev/staging.Dockerfile) is the file in question and it'll be available on the `staging` branch after we merge this: https://github.com/databio/refgenieserver/pull/43

**Comment by stolarczyk** [comment]
Also, the `refgenieserver` command syntax has changed on `dev`; the config file will need to be specified after the positional argument `serve`, like this:

```
refgenieserver serve -c /genomes/genomes_staging.yaml
```

**Comment by stolarczyk** [comment]
> after we merge this: #43

done

**Comment by nsheff** [comment]
> dditionally, we'd like to use a separate Dockerfile for the staging container, since we expect to test non-released requirements of refgenieserver. Do you think you can set it up this way?
staging.Dockerfile is the file in question 

@michalstolarczyk 

I think you can just change this line: 

https://github.com/databio/refgenieserver/blob/07b44a086c0a9c67ef381f9ae03ace5b35c3b72b/.travis.yml#L25

**Comment by stolarczyk** [comment]
that's right we'll need to add `-f staging.Dockerfile` there, but `refgenieserver` would still get the old config (v0.2), which would result in `ConfigNotCompliantError`

and most importantly `-c` would be passed before `serve`

**Comment by nsheff** [comment]
@nmagee is there any way for us to change it from `genomes.yaml` to `genomes_staging.yaml` ? Or are you the only one who can do it?

**Comment by nmagee** [comment]
Let’s have a session together this week to get you guys in DCOS so you can modify / scale / manage as you need to. I hate being a roadblock!
