### ISSUE TITLE
version API

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#42]
Some reading: 

https://stackoverflow.com/questions/389169/best-practices-for-api-versioning

https://www.troyhunt.com/your-api-versioning-is-wrong-which-is/

### idea:

change `main.py` to:

```
from .version1 import *
from .version2 import *
```
and `version1.py` is:

```
VERSION="v1"
@app.get("/")
@app.get(os.path.join(VERSION, "/index"))
async def index(request: Request):
```

Then refgenconf says `VERSION="v1"` and can be updated as needed.

**Comment by stolarczyk** [comment]
implemented using [`fastapi.APIRouter`](https://fastapi.tiangolo.com/tutorial/bigger-applications/#apirouter) objects
