### ISSUE TITLE
add hook to list genomes by asset

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#5]
once refgenieconf has list genomes by asset function, https://github.com/databio/refgenconf/issues/7

there should be an endpoint to access that.

**Comment by nsheff** [comment]
looks like this can now be done with the latest refgenconf: https://github.com/databio/refgenconf/issues/7

**Comment by stolarczyk** [comment]
it can be accessed now at: `/genomes/{asset}`

**question**: do we raise a 404 exception when there are no genomes with requested asset or return an empty list (which `list_genomes_by_asset` method does by default)?

**Comment by nsheff** [comment]
> do we raise a 404 exception when there are no genomes with requested asset or return an empty list 

return empty list.
