### ISSUE TITLE
Refgenomes.databio.org master server is giving a 404 error

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#51]
http://refgenomes.databio.org/ is down.

It was actually down (giving a 404 error) before the release... but anyway, now I just released it and it's still down...

**Comment by nsheff** [comment]
http://staging.refgenomes.databio.org/ is operating as normal

**Comment by nsheff** [comment]
The container is healthy and is serving correctly at: http://refgenomes.uvadcos.io/

Maybe it's just a cache issue but it's not showing up yet at the databio.org subdomain...

**Comment by stolarczyk** [comment]
Oh so it worked... the release I've just made fixed it. 

I wasn't sure why it's not up at our main URL

**Comment by nsheff** [comment]
@nmagee is it working for you?

**Comment by nsheff** [comment]
BTW, it was down before we did the release @michalstolarczyk so I don't think it's related to your fix, tbh...

**Comment by stolarczyk** [comment]
I've browsed the logs when it was down after our first release today (v0.3.0) and the there was an `ImportError` regarding `refgenconf`. v0.3.0 was released with a `refgenconf` requirement commented out so it was not installed in the container build from the main Dockerfile. This was not the case on staging, because of this additional line in staging.Dockerfile:
```
RUN pip install https://github.com/databio/refgenconf/archive/dev.zip
```

But why it was down before? I have no idea

**Comment by nmagee** [comment]
Hi guys, sorry I was out of pocket all day in an ACCORD kickoff meeting. Looks like we’ve had an issue in Marathon that is not letting new services deploy or restart properly. I’ll dig into this and remedy as soon as I can, and open a ticket with Mesosphere if needed.

**Comment by nsheff** [comment]
Ok thanks. It's not just a caching issue, because it's still down here at my home computer as well. So, there's definitely something wrong in mesos.

it's strange that it's working at some URLs but not others.

**Comment by nsheff** [comment]
I noticed the DNS was set differently (probably set at different times)...

refgenomes.databio.org had an A record to 128.143.8.170 while staging had a CNAME to ladbalancer.uvadcos.io

```
dig refgenomes.databio.org

; <<>> DiG 9.10.3-P4-Ubuntu <<>> refgenomes.databio.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1918
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;refgenomes.databio.org.		IN	A

;; ANSWER SECTION:
refgenomes.databio.org.	1324	IN	A	128.143.8.170

;; Query time: 1 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Tue Oct 22 07:51:19 EDT 2019
;; MSG SIZE  rcvd: 67
```

```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> staging.refgenomes.databio.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56066
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;staging.refgenomes.databio.org.	IN	A

;; ANSWER SECTION:
staging.refgenomes.databio.org.	1113 IN	CNAME	loadbalancer.uvadcos.io.
loadbalancer.uvadcos.io. 29	IN	A	128.143.245.182
loadbalancer.uvadcos.io. 29	IN	A	128.143.245.181

;; Query time: 1 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Tue Oct 22 07:48:03 EDT 2019
;; MSG SIZE  rcvd: 128
```


Meanwhile refgenomes.uvadcos.io has A records that match the loadbalancer settings: 

```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> refgenomes.uvadcos.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24772
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;refgenomes.uvadcos.io.		IN	A

;; ANSWER SECTION:
refgenomes.uvadcos.io.	60	IN	A	128.143.245.182
refgenomes.uvadcos.io.	60	IN	A	128.143.245.181

;; Query time: 4 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Tue Oct 22 07:55:49 EDT 2019
;; MSG SIZE  rcvd: 82
```

I've changed the main one to match the CNAME version. Any reason this changed sometime yesterday?

**Comment by nsheff** [comment]
And, now it's resolving correctly. That was quick... only took about 5 min to propagate.
