### ISSUE TITLE
hg19 ensembl_gtf asset is incorrect

### ISSUE THREAD

**Issue by jpsmith5** [databio/refgenieserver#61]
It appears that the `ensembl_gtf` asset for hg19 is either the wrong initial file or something was changed to it along the way. It should contain the following identifiers in column 3:
```
gzip -dc ensembl_gtf/hg19.gtf.gz | awk '{print $3}' | sort -u

CDS
exon
five_prime_utr
gene
Selenocysteine
start_codon
stop_codon
three_prime_utr
transcript
```

But instead it has:
```
CDS
exon
gene
Selenocysteine
start_codon
stop_codon
transcript
UTR
```

Checking the [original source file](https://bit.ly/2MUP72j), as [we reference in the docs](http://refgenie.databio.org/en/dev/available_assets/#fasta), includes the "correct" values.  Not sure what the original file from http://refgenomes.databio.org is derived from...

**Comment by nsheff** [comment]
It should come from here: 

https://github.com/databio/databio_genomes

it appears to be using: ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz

I can't tell what you're suggesting to use because the URL is masked by bit.ly. is it incorrect?

**Comment by jpsmith5** [comment]
ftp://ftp.ensembl.org/pub/grch37/current/gtf/homo_sapiens/Homo_sapiens.GRCh37.87.gtf.gz is the link and includes the correct file structure. Never tested it on older releases.

**Comment by jpsmith5** [comment]
Regarding never testing. That is to say, building the `feat_annotation` asset fails with that version of the file because it does not contain the full annotations.

**Comment by nsheff** [comment]
I see. I guess this explains why there is no feat_annotation asset currently being served for hg19. So, what needs to happen is:

1. update the [genomes repo](https://github.com/databio/databio_genomes) to the new URL
2. delete the current hg19/ensembl_gtf asset
3. re-build that asset, and hg19/feat_annotation
4. re-archive those 2 assets.

**Comment by jpsmith5** [comment]
:thumbsup: will do

**Comment by nsheff** [comment]
closing issue, please re-open if this is still a problem.
