### ISSUE TITLE
serve headers to files correctly

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#68]
duh ! My bad, there was no extensions to the file when downloaded with wget so I assumed just gzipped. Thanks for the heads up.

_Originally posted by @k3yavi in https://github.com/databio/refgenieserver/issues/63#issuecomment-561340029_

I can confirm that wget isn't getting the correct info. Can we update the headers on refgenieserver?

```
wget http://staging.refgenomes.databio.org/v2/asset/mm10/fasta/archive?tag=default
--2019-12-03 15:41:21--  http://staging.refgenomes.databio.org/v2/asset/mm10/fasta/archive?tag=default
Resolving staging.refgenomes.databio.org (staging.refgenomes.databio.org)... 128.143.245.182, 128.143.245.181
Connecting to staging.refgenomes.databio.org (staging.refgenomes.databio.org)|128.143.245.182|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 800557520 (763M) [application/octet-stream]
Saving to: ‘archive?tag=default’

archive?tag=default        36%[============>                         ] 275.37M  28.3MB/s    eta 18s    ^C
```

I don't remember how to do this off the top of my head but there's surely a way to put headers on these files so that they are correctly interpreted by tools like wget...

**Comment by nsheff** [comment]
apparently this is intended... you have to use `wget --content-disposition` if you want to use the server-suggested name 

https://unix.stackexchange.com/questions/453465/wget-how-to-download-a-served-file-keeping-its-name

So, nevermind. we are already doing it correctly, it's just a wget behavior thing.

**Comment by k3yavi** [comment]
Oh, I wasn't aware of that flag, thanks @nsheff !!
