### ISSUE TITLE
archiving with multicore

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#83]
what do you think of somehow speeding up the archive process with pigz?

https://stackoverflow.com/questions/12313242/utilizing-multi-core-for-targzip-bzip-compression-decompression

**Comment by stolarczyk** [comment]
`pigz` is already used, if available:

https://github.com/databio/refgenieserver/blob/52ed2869ac1b049bba97b31cb706da41cc3ca395/refgenieserver/server_builder.py#L216

**Comment by nsheff** [comment]
ah; must not have been available, then...
