### ISSUE TITLE
remote url pointers are incomplete

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#86]
Right now on staging, the remotes are correct for the big archive file, but we need to *also* update the URLs for the other files, which are no longer stored locally... that would be the endpoints for build log and build recipe.

You can see it in action here: http://rg.databio.org:82/

@stolarczyk do you think you can handle this change?

**Comment by nsheff** [comment]
those files *are* on aws, so we just need to update the code to point to aws not just for the archive, but for any files served by the api

**Comment by stolarczyk** [comment]
sure, I'll get all the API endpoints to work with remote_url pointer
