### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#9]
I originally used `refgenie_server` as the name of this repository, and then used `refgenies` as the command to invoke to start the server.

I'm not sure if `refgenies` is good because it is just *so* close to refgenie that it may cause some confusion.

I wanted to see what you thought about this and if you had any other suggestion for CLI name.

some ideas:
- `refgenserve`
- `rgserver` 
- `rgcserver`
- `refgenieserver`

I'm leaning toward `rgserver`  for the command name....

**Comment by stolarczyk** [comment]
I like `refgenieserver` the most

**Comment by vreuter** [comment]
Ditto to @michalstolarczyk

**Comment by nsheff** [comment]
the command would then be `refgenieserver serve` and `refgenieserver archive`. that's good?

**Comment by stolarczyk** [comment]
LMK if I can proceed with the repo/command name change

**Comment by nsheff** [comment]
it's not my favorite but since you both vote for it, I'm on board. Go for it!

the repo should also change names to that then
