### ISSUE TITLE
/asset endpoint lists seek keys

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#93]
this asset endpoint: http://refgenomes.databio.org/v2/assets

will yield a response not for every asset but for every seek key. This causes some confusion... shoudl the asset endpoint only list assets? why would we want seek keys listed here? should it be a separate endpoint?

raised in discussion with @natefoo

**Comment by nsheff** [comment]
alternatively, listr doesn't need to show the seek keys.
what is the advantage of showing seek keys in listr ? people are interested in the assets, not the seek keys, held by the server.

**Comment by stolarczyk** [comment]
I think listing seek keys makes sense because soon the asset recipes and names will become arbitrary so this is a way to remotely inspect actual contents of an asset. Additionally, I like that list and listr show the same _types_ of information
