### ISSUE TITLE
genome mapping endpoint link

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#98]
![image](https://user-images.githubusercontent.com/5271009/91600712-6fb72200-e936-11ea-8a33-4effef826a32.png)

why does every asset have a 'genomes mapping' endpoint link, when this is universal and not asset-specific?

**Comment by nsheff** [comment]
eg http://refgenomes.databio.org:84/v3/asset/01139a772b15031670b3517b4b81cb26cc3eeba98b9699ab/fasta/splash?tag=default

**Comment by stolarczyk** [comment]
I added the "genome attributes" and "genomes mapping" enpoints by mistake. This list of links is generated systematically from a dict defined in refgenconf. By adding those links to the dict, the error propagated.

**Comment by nsheff** [comment]
makes sense. thanks!
